- README.md
- build.gradle
- src/main/java/io/github/iprodigy/cache/CacheApi.java
- src/main/java/io/github/iprodigy/cache/CacheApiSpec.java
- src/main/java/io/github/iprodigy/cache/ICacheSpec.java
- src/main/java/io/github/iprodigy/cache/providers/AbstractCacheProvider.java
- src/main/java/io/github/iprodigy/cache/providers/AndroidExpiringLruProvider.java
- src/main/java/io/github/iprodigy/cache/providers/AndroidLruProvider.java
- src/main/java/io/github/iprodigy/cache/providers/CacheProvider.java
- src/main/java/io/github/iprodigy/cache/providers/CaffeineProvider.java
- src/main/java/io/github/iprodigy/cache/providers/EhcacheProvider.java
- src/main/java/io/github/iprodigy/cache/providers/ExpiringMapProvider.java
- src/main/java/io/github/iprodigy/cache/providers/GenericMapCacheDelegate.java
- src/main/java/io/github/iprodigy/cache/providers/GuavaProvider.java
- src/main/java/io/github/iprodigy/cache/providers/InfinispanProvider.java
- src/test/java/io/github/iprodigy/cache/CacheApiTest.java
- replace the builder with a spec consumer
- add slf4j / slf4j-simple for tests
> feat: replace builder with spec consumer

- build.gradle.kts
Published snapshot: https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/xanthic/cache/
> build: add signing and maven publish plugins

- bom/build.gradle.kts
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/globals.kt
- buildSrc/src/main/kotlin/maven.kt
- settings.gradle.kts
will publish a `cache-bom` artifact, we could also add constraints on external deps here (maybe for the cache impl)
> feat: add bom publication

- core/src/main/java/io/github/xanthic/cache/core/AbstractCacheProvider.java
- core/src/main/java/io/github/xanthic/cache/core/CacheApiSettings.java
> refactor: remove defaultExpiryType

- bom/build.gradle.kts
- build.gradle.kts
- uses the `java-platform` plugin to generate the bom
> feat: use java-platform plugin for bom

- kotlin/src/main/kotlin/io/github/xanthic/cache/ktx/CacheApiExtensions.kt
- kotlin/src/test/kotlin/io/github/xanthic/cache/ktx/KotlinTest.kt
https://kotlinlang.org/docs/operator-overloading.html
> feat(kotlin): define cache operator overloads

- .github/workflows/gradle.yml
- renovate.json
- settings.gradle.kts
- spring-java17/build.gradle.kts
- spring-java17/src/main/java/io/github/xanthic/cache/springjdk17/XanthicSpringCache.java
- spring-java17/src/main/java/io/github/xanthic/cache/springjdk17/XanthicSpringCacheManager.java
- spring-java17/src/test/java/io/github/xanthic/cache/springjdk17/SpringCacheTest.java
- spring-java17/src/test/java/io/github/xanthic/cache/springjdk17/config/CacheConfiguration.java
> feat: add spring java 17 module

- build.gradle.kts
https://www.jacoco.org/jacoco/trunk/doc/changes.html
> chore: bump jacoco to 0.8.10

- build.gradle.kts
https://projectlombok.org/changelog
> chore(deps): update lombok to 1.18.28

- bom/build.gradle.kts
This makes the bom module list dynamic to replace the hardcoded list.
This should be easier to maintain, as a few were still missing:
- spring
- spring-17
- infinispan-java11
- (jackson)
> fix: set bom modules dynamically

- build.gradle.kts
https://projectlombok.org/changelog
> chore: update lombok to v1.18.30

- README.md
- build.gradle.kts
https://github.com/Xanthic/cache-api/compare/0.3.0...48356e68cfd57b4090a7d9e2a650782caa0a6f85
> chore: release xanthic v0.4.0

- provider-infinispan-java11/src/main/java/io/github/xanthic/cache/provider/infinispanjdk11/InfinispanProvider.java
- provider-infinispan/src/main/java/io/github/xanthic/cache/provider/infinispan/InfinispanProvider.java
https://infinispan.org/docs/14.0.x/titles/configuring/configuring.html#simple-caches_caches
> perf(infinispan): use simpler, non-clustered cache

- provider-cache2k/src/main/java/io/github/xanthic/cache/provider/cache2k/Cache2kProvider.java
Cache2k enables statistics by default, and we don't offer an interface to access these statistics, so we can disable statistics for a performance boost.
In addition, when time-based expiry is not enabled, we can specify the eternal hint as another optimization (note: this correctly does not prevent size-based evictions).
> perf(cache2k): disable statistics and configure eternal

- README.md
- build.gradle.kts
https://github.com/Xanthic/cache-api/compare/v0.4.1...944a8898a5d77c04cda411caf7621da6202f5808
> chore: release xanthic v0.4.2

- README.md
- core/src/main/java/io/github/xanthic/cache/core/CacheApiSettings.java
- provider-infinispan-java17/build.gradle.kts
- provider-infinispan-java17/src/main/java/io/github/xanthic/cache/provider/infinispanjdk17/InfinispanDelegate.java
- provider-infinispan-java17/src/main/java/io/github/xanthic/cache/provider/infinispanjdk17/InfinispanListener.java
- provider-infinispan-java17/src/main/java/io/github/xanthic/cache/provider/infinispanjdk17/InfinispanProvider.java
- provider-infinispan-java17/src/test/java/io/github/xanthic/cache/provider/infinispanjdk17/InfinispanJava17ProviderTest.java
- settings.gradle.kts
https://infinispan.org/blog/2024/03/13/infinispan-15
code on our end is the exact same as java11 module
> feat: add infinispan jdk17 module

- README.md
- build.gradle.kts
https://github.com/Xanthic/cache-api/compare/v0.5.0...ed1eb3097ee0d3c013be9e9376fee83679ee0507
> chore: release xanthic v0.6.0

- build.gradle.kts
https://projectlombok.org/changelog
> chore: bump lombok to v1.18.34

- kotlin/src/main/kotlin/io/github/xanthic/cache/ktx/CacheApiSpecExtensions.kt
Adds kotlin convenience property after #186
> feat(kotlin): expose highContention spec as property

- README.md
- build.gradle.kts
https://github.com/Xanthic/cache-api/compare/v0.6.1...1675da2c292efa8fe9ac8be7adaa6b9a03e8993e
>  chore: prepare xanthic v0.6.2 release

- core/src/main/java/io/github/xanthic/cache/core/AbstractCacheProvider.java
- core/src/main/java/io/github/xanthic/cache/core/CacheApiSettings.java
- core/src/test/java/io/github/xanthic/cache/core/provider/SimpleMapProvider.java
- provider-androidx/src/main/java/io/github/xanthic/cache/provider/androidx/AndroidLruProvider.java
- provider-androidx/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-cache2k/src/main/java/io/github/xanthic/cache/provider/cache2k/Cache2kProvider.java
- provider-cache2k/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-caffeine/src/main/java/io/github/xanthic/cache/provider/caffeine/CaffeineProvider.java
- provider-caffeine/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-caffeine3/src/main/java/io/github/xanthic/cache/provider/caffeine3/Caffeine3Provider.java
- provider-caffeine3/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-ehcache/src/main/java/io/github/xanthic/cache/provider/ehcache/EhcacheProvider.java
- provider-ehcache/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-expiringmap/src/main/java/io/github/xanthic/cache/provider/expiringmap/ExpiringMapProvider.java
- provider-expiringmap/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-guava/src/main/java/io/github/xanthic/cache/provider/guava/GuavaProvider.java
- provider-guava/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-infinispan-java11/src/main/java/io/github/xanthic/cache/provider/infinispanjdk11/InfinispanProvider.java
- provider-infinispan-java11/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-infinispan-java17/src/main/java/io/github/xanthic/cache/provider/infinispanjdk17/InfinispanProvider.java
- provider-infinispan-java17/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
- provider-infinispan/src/main/java/io/github/xanthic/cache/provider/infinispan/InfinispanProvider.java
- provider-infinispan/src/main/resources/META-INF/services/io.github.xanthic.cache.core.AbstractCacheProvider
> feat: #246 - Use ServiceLoader to discover and register Xanthic Cache Providers
