Xanthic/cache-api

- provider-androidx/src/main/java/io/github/iprodigy/cache/provider/androidx/AndroidExpiringLruProvider.java
- provider-androidx/src/main/java/io/github/iprodigy/cache/provider/androidx/ExpiringLruDelegate.java
Ensure `RemovalCause` is `TIME` for an entry being removed by the expiration task (previously was just `MANUAL`)
> fix: distinguish expired removals for androidx listener

- provider-androidx/src/main/java/io/github/iprodigy/cache/provider/androidx/AndroidLruProvider.java
- provider-cache2k/src/main/java/io/github/iprodigy/cache/provider/cache2k/Cache2kProvider.java
https://cache2k.org/docs/latest/apidocs/cache2k-api/org/cache2k/Cache2kBuilder.html#idleScanTime(java.time.Duration)
> fix(cache2k): target correct access expiry time

- README.md
- kotlin/build.gradle.kts
- kotlin/src/main/kotlin/io/github/xanthic/cache/ktx/CacheApiExtensions.kt
- kotlin/src/main/kotlin/io/github/xanthic/cache/ktx/CacheApiSpecExtensions.kt
- kotlin/src/test/kotlin/io/github/xanthic/cache/ktx/KotlinTest.kt
- settings.gradle.kts
WIP: the KDoc comments are not yet copying over to the javadoc jar (🤔) — edit: appears to be caused by https://github.com/Kotlin/dokka/issues/1908
> feat: create kotlin extensions module

- core/src/main/java/io/github/xanthic/cache/core/CacheApiSettings.java
- core/src/main/java/io/github/xanthic/cache/core/CacheApiSpec.java
- kotlin/src/main/kotlin/io/github/xanthic/cache/ktx/CacheApiSpecExtensions.kt
- annotate CacheApiSpec.Provider as NotNull
- don't log the full ClassNotFound exception when looking for cache providers
> chore: provider may not be null

- core/src/main/java/io/github/xanthic/cache/core/AbstractCache.java
- core/src/main/java/io/github/xanthic/cache/core/LockedAbstractCache.java
- provider-ehcache/src/main/java/io/github/xanthic/cache/provider/ehcache/EhcacheDelegate.java
For `compute`, `computeIfAbsent`, `computeIfPresent`, and `merge`, Ehcache itself does not implement these operations. As a result, `AbstractCache` implementations were used, but these require other writes to use the same synchronization lock object. (In the pursuit of performance) `EhcacheDelegate` did not lock synchronize possibly concurrent writes, which could hamper the correctness of `compute`, `computeIfAbsent`, `computeIfPresent`, and `merge`.
Now, `ReentrantReadWriteLock` is used to achieve correctness for these cache functions in a multi-threaded environment, without sacrificing as much performance (as blunt synchronization would entail).
> fix(ehcache): properly lock on special writes

- README.md
- build.gradle.kts
Minor bump due to new module, while avoiding breaking changes
> chore: bump xanthic to 0.2.0

- renovate.json
- make renovate use `chore(deps): ` instead of `fix(deps): `
> chore: use chore commit type for renovate updates

- renovate.json
Avoids https://github.com/Xanthic/cache-api/pull/133/commits/2cfd5e7441279cb5c4882a98446acbcda02105fa
> chore: avoid infinispan major version bumps for java 8 module

- README.md
- build.gradle.kts
* perf(spring): avoid lock contention when obtaining cache in https://togithub.com/Xanthic/cache-api/pull/109
* feat: add infinispan java 11 module in https://togithub.com/Xanthic/cache-api/pull/132
* feat: add spring java 17 module in https://togithub.com/Xanthic/cache-api/pull/135
&nbsp;
Will require new docs pages
> chore: bump xanthic to 0.3.0

- core/src/main/java/io/github/xanthic/cache/core/CacheApi.java
- core/src/main/java/io/github/xanthic/cache/core/delegate/EmptyCache.java
- core/src/testFixtures/java/io/github/xanthic/cache/core/provider/ProviderTestBase.java
Some users may do `maxSize(0L)` or `expiryTime(Duration.ZERO)` to "disable" caching.
However, this is not supported by all of the underlying providers: https://togithub.com/FasterXML/jackson-databind/pull/4115#discussion_r1335062530
This PR returns `EmptyCache.INSTANCE` in these scenarios to avoid exceptions/inconsistency across providers.
> fix(core): allow zero max size caches across providers

- api/src/main/java/io/github/xanthic/cache/api/Cache.java
- core/src/main/java/io/github/xanthic/cache/core/delegate/EmptyCache.java
- core/src/main/java/io/github/xanthic/cache/core/delegate/GenericMapCacheDelegate.java
- core/src/testFixtures/java/io/github/xanthic/cache/core/provider/ProviderTestBase.java
- provider-androidx/src/main/java/io/github/xanthic/cache/provider/androidx/ExpiringLruDelegate.java
- provider-androidx/src/main/java/io/github/xanthic/cache/provider/androidx/LruDelegate.java
- provider-cache2k/src/main/java/io/github/xanthic/cache/provider/cache2k/Cache2kDelegate.java
- provider-ehcache/src/main/java/io/github/xanthic/cache/provider/ehcache/EhcacheDelegate.java
- provider-infinispan-java11/src/main/java/io/github/xanthic/cache/provider/infinispanjdk11/InfinispanDelegate.java
- provider-infinispan/src/main/java/io/github/xanthic/cache/provider/infinispan/InfinispanDelegate.java
Currently experimental/optional - in 1.0.0, we can decide whether to promote to stable/required
Required for upcoming jackson module since https://github.com/FasterXML/jackson-databind/pull/4114 / https://github.com/FasterXML/jackson-databind/blob/2.16/src/main/java/com/fasterxml/jackson/databind/ser/impl/ReadOnlyClassToSerializerMap.java#L30
> feat(api): add forEach method to Cache interface

- provider-cache2k/src/main/java/io/github/xanthic/cache/provider/cache2k/Cache2kProvider.java
When `ICacheSpec#maxSize` yields null, an unbounded cache should be created. By default, cache2k imposes an `entryCapacity` of [1802](https://cache2k.org/docs/latest/apidocs/cache2k-api/org/cache2k/config/Cache2kConfig.html#DEFAULT_ENTRY_CAPACITY) (rather than creating an unbounded cache). As a result, we specify `Long.MAX_VALUE` to create an unbounded cache when `maxSize` is null, in accordance to the Xanthic spec.
https://cache2k.org/docs/latest/apidocs/cache2k-api/org/cache2k/Cache2kBuilder.html#entryCapacity(long)
> fix(cache2k): create unbounded cache if maxSize is not specified

- api/src/main/java/io/github/xanthic/cache/api/ICacheSpec.java
- core/src/main/java/io/github/xanthic/cache/core/CacheApiSpec.java
- core/src/testFixtures/java/io/github/xanthic/cache/core/provider/ProviderTestBase.java
- provider-cache2k/src/main/java/io/github/xanthic/cache/provider/cache2k/Cache2kProvider.java
- provider-ehcache/src/main/java/io/github/xanthic/cache/provider/ehcache/EhcacheProvider.java
- provider-guava/src/main/java/io/github/xanthic/cache/provider/guava/GuavaProvider.java
Add `ICacheSpec#highContention`, which can enable the following optimizations
* Cache2k: `boostConcurrency`
* Guava: `concurrencyLevel`
* Ehcache: `TickingTimeSource`
> feat: add high contention hint to cache spec

- core/src/main/java/io/github/xanthic/cache/core/LockedAbstractCache.java
- provider-ehcache/src/main/java/io/github/xanthic/cache/provider/ehcache/EhcacheDelegate.java
- provider-ehcache/src/main/java/io/github/xanthic/cache/provider/ehcache/EhcacheProvider.java
Rewrites EhcacheDelegate without `ReadWriteLock` - achieves 10x throughput in certain multi-threaded benchmarks
> perf(ehcache): avoid coarse locking

- build.gradle.kts
sets the properties to enable reproducible builds, see https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
we can try to set this up with https://github.com/jvm-repo-rebuild/reproducible-central / https://reproducible-builds.org/ for the next release.
> chore: enable reproducible archives

- spring-java17/src/main/java/io/github/xanthic/cache/springjdk17/XanthicSpringCache.java
- spring-java17/src/test/java/io/github/xanthic/cache/springjdk17/SpringCacheTest.java
- spring/src/main/java/io/github/xanthic/cache/spring/XanthicSpringCache.java
* Implement new `CompletableFuture` versions of lookup that were added to the Cache interface in spring context v6.1,
* Explicitly implement `evictIfPresent` so the return value contains more information (previously would always return false)
* Explicitly implement `putIfAbsent` so the operation is atomic (default impl is non-atomic)
> feat(spring): implement optional cache methods

- README.md
- build.gradle.kts
https://github.com/Xanthic/cache-api/compare/v0.4.2...0409b2ce3a7100b8c12bf5af2cdbdc706d9b4fab
> chore: release xanthic v0.5.0

- build.gradle.kts
Since [Reproducible Central](https://github.com/jvm-repo-rebuild/reproducible-central/) doesn't have GPG creds to sign the main publication, build failures occur when trying to publish to maven local (even with `-x signMainPublication`). 
Instead, we can skip signing if creds are absent: https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing
> chore: utilize conditional signing

- .github/workflows/gradle.yml
https://github.com/actions/checkout/releases/tag/v4.1.3
https://github.com/actions/setup-java/releases/tag/v4.2.1
https://github.com/gradle/actions/releases/tag/v3.3.1 (updated from [v2.2.1](https://github.com/gradle/gradle-build-action/releases/tag/v2.2.1))
> chore: pin gh action versions

- .github/workflows/gradle.yml
https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated
> chore(ci): avoid deprecated gradle arguments parameter

- spring-java17/src/main/java/io/github/xanthic/cache/springjdk17/XanthicSpringCache.java
- spring/src/main/java/io/github/xanthic/cache/spring/XanthicSpringCache.java
See https://github.com/spring-projects/spring-framework/blob/d2ea5b444812b4c55e00fecb7b6451073677061d/spring-context/src/main/java/org/springframework/cache/concurrent/ConcurrentMapCache.java#L148-L157 / https://github.com/spring-projects/spring-framework/blob/d2ea5b444812b4c55e00fecb7b6451073677061d/spring-context-support/src/main/java/org/springframework/cache/caffeine/CaffeineCache.java#L134-L136
* need `fromStoreValue` in case `NullValue.INSTANCE` is stored
* need `toStoreValue` in case `valueLoader` yields null
* can remove synchronization since most underlying providers already lock the table segment as needed
> fix(spring): improve null safety for cache get with loader

- build.gradle.kts
useful for https://github.com/jvm-repo-rebuild/reproducible-central to avoid `signMainPublication > A problem occurred starting process 'command 'gpg''`
> chore(build): allow signing with pgp or gpg

- core/src/main/java/io/github/xanthic/cache/core/LockedAbstractCache.java
- provider-androidx/src/main/java/io/github/xanthic/cache/provider/androidx/AbstractCache.java
- provider-androidx/src/main/java/io/github/xanthic/cache/provider/androidx/ExpiringLruDelegate.java
- provider-androidx/src/main/java/io/github/xanthic/cache/provider/androidx/LruDelegate.java
Caches typically shouldn't use `AbstractCache` due to its use of synchronization (bad for multi-threaded performance and virtual threads pre JEP 8337395)
We only use it for the android module since the underlying LruCache also synchronizes all operations, so I've copied the class to a package-private form for that module
> chore: deprecate AbstractCache that relies upon synchronization

- core/src/main/java/io/github/xanthic/cache/core/CacheApiSettings.java
- core/src/test/java/io/github/xanthic/cache/core/CacheRegistrationTest.java
avoids `volatile` and `synchronized`, while maintaining thread safety and lazy loading
> perf: simplify CacheApiSettings singleton creation

- spring-java17/src/main/java/io/github/xanthic/cache/springjdk17/CacheWrapper.java
- spring-java17/src/main/java/io/github/xanthic/cache/springjdk17/XanthicSpringCacheManager.java
- spring-java17/src/test/java/io/github/xanthic/cache/springjdk17/SpringCacheTest.java
- spring/src/main/java/io/github/xanthic/cache/spring/CacheWrapper.java
- spring/src/main/java/io/github/xanthic/cache/spring/XanthicSpringCacheManager.java
- spring/src/test/java/io/github/xanthic/cache/spring/SpringCacheTest.java
See https://github.com/spring-projects/spring-framework/commit/022fdcd67ee4811a5e73e5495280f26149b7446f and https://github.com/Xanthic/cache-api/pull/350#pullrequestreview-2455875574
> feat(spring): add removeCache method to cache manager

- kotlin/build.gradle.kts
See https://github.com/jvm-repo-rebuild/reproducible-central/pull/1363
https://youtrack.jetbrains.com/issue/KT-54207/Kotlin-has-two-sources-tasks-kotlinSourcesJar-and-sourcesJar-that-archives-sources-to-the-same-artifact
https://redirect.github.com/micrometer-metrics/micrometer/issues/5151
>  chore: restore reproducibility of kotlin sources jar 

- core/src/main/java/io/github/xanthic/cache/core/CacheApiSettings.java
Follow-up to #367
* Improve servlet compatibility by specifying the class loader
* Add `SecurityManager` support
* Ensure consistent registration order (alphabetic) when multiple providers have the same discovery priority
* Catch `ServiceConfigurationError` to prevent a misconfigured cache provider from breaking all of xanthic
> refactor(core): improve safety of service loader usage
